services:
  db:
    image: postgres
    restart: always
    env_file: ".env"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d

  pgadmin:
    image: dpage/pgadmin4:latest
    env_file: ".env"
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  pgdata:
