services:
  db:
    image: postgres:16
    restart: always
    env_file: ".env"
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    networks:
      - trading_net

  pgadmin:
    image: dpage/pgadmin4:latest
    env_file: ".env"
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - trading_net

  airflow-webserver:
    build: .
    restart: always
    env_file: ".env"
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: ${AIRFLOW_DB_CONN}
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      PYTHONPATH: /opt/airflow
      POSTGRES_HOST: db
    volumes:
      - ./dags:/opt/airflow/dags
      - ./src:/opt/airflow/src
      - ./logs:/opt/airflow/logs
      - ./market_data:/opt/airflow/market_data
    ports:
      - "8080:8080"
    depends_on:
      - db
    command: webserver
    networks:
      - trading_net

  airflow-scheduler:
    build: .
    restart: always
    env_file: ".env"
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: ${AIRFLOW_DB_CONN}
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      PYTHONPATH: /opt/airflow
      POSTGRES_HOST: db
    volumes:
      - ./dags:/opt/airflow/dags
      - ./src:/opt/airflow/src
      - ./logs:/opt/airflow/logs
      - ./market_data:/opt/airflow/market_data
    depends_on:
      - db
    command: scheduler
    networks:
      - trading_net

  airflow-init:
    build: .
    env_file: ".env"
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: ${AIRFLOW_DB_CONN}
      POSTGRES_HOST: db
    depends_on:
      - db
    command: >
      bash -c "airflow db init &&
                airflow users create --username admin --password admin
                --firstname Admin --lastname User
                --role Admin --email admin@example.com"
    networks:
      - trading_net

networks:
  trading_net:

volumes:
  pgdata:
